/* use std::arch::global_asm;
use std::collections::HashMap;
use std::f32::consts::E; */

use crate::utils::bow::*;
use crate::utils::fs::*;
use crate::utils::regex::*;
use crate::utils::{/* csv::*,  */ logger::Logger};
use anyhow::{anyhow, /*bail, Context,  */ Result};
use tracing::info;
/* use clang::token;
use polars::frame::row; */
use clap::{Arg, /* ArgAction, */ Command};
use polars::prelude::*;
use std::collections::HashMap;
/* struct Token {
    word: Vec<u8>,
    local_count: usize,
    global_count: usize,
    global_position: usize,
} */

pub fn cli() -> Command {
    Command::new("tokenizer")
        .about("Tokenizes the functions in the input file and generates a global Bag of Words.")
        .disable_version_flag(true)
        .arg(
            Arg::new("input")
                .short('i')
                .long("input")
                .value_name("INPUT_PATH")
                .help("Path to the input CSV file generated by the parser.")
                .required(true),
        )
        .arg(
            Arg::new("example_word")
                .short('e')
                .long("example-word")
                .value_name("EXAMPLE_WORD")
                .help("An example word to check the global Bag of Words for.")
                .required(false),
        )
}

pub fn run(input_path: &str, example_word: &str, logger: &Logger) -> Result<()> {
    let language = "java";
    let minimum_loc = 5; //temporary
                         //let separators = vec!["(", ")", "[", "]", "{", "}", ";", ".", ",", ":", "=", "+", "-", "*", "/", "%", "<", ">", "&", "|", "!", "?", "~", "^", "#", "$", "@", "\"", "\\", "`", "'"]; //hardcoded separators for now. Will add more later and make it configurable.

    let mut input_file = open_csv(
        input_path,
        Some(Schema::from_iter(vec![
            Field::new("id".into(), DataType::UInt32),
            Field::new("path".into(), DataType::String),
            Field::new("name".into(), DataType::String),
            Field::new("position".into(), DataType::String),
            Field::new("loc".into(), DataType::UInt32),
            Field::new("words".into(), DataType::UInt32),
        ])),
        Some(vec![
            "id", "path", "name", "position", "language", "loc", "words",
        ]),
    )?;

    let n_functions_before_language = input_file.height();
    info!(
        "{} functions found in the input file, filtering by selected language",
        n_functions_before_language
    );

    //input_file = input_file.filter(&input_file.column("language")?.equal(language));
    input_file = input_file
        .lazy()
        .filter(col("language").eq(lit(language)))
        .collect()?;

    let n_functions_after_language = input_file.height();
    info!(
        "  {} files found after filtering ({:.2} %)",
        n_functions_after_language,
        if n_functions_before_language == 0 {
            0
        } else {
            n_functions_after_language / n_functions_before_language * 100
        }
    );
    let n_functions_before_loc = input_file.height();

    info!(" {} functions found after filtering by language, filtering functions with less that {} lines of code.", n_functions_before_loc, minimum_loc);

    //input_file = input_file.filter(&input_file.column("loc")?.greater_equal(minimum_loc))?;

    input_file = input_file
        .lazy()
        .filter(col("loc").gt_eq(lit(minimum_loc)))
        .collect()?;

    let n_functions_after_loc = input_file.height();

    info!(
        "{} functions found after filtering  ({:.2} %)", //something is weird with the percentage calculation here.
        n_functions_after_loc,
        if n_functions_before_loc == 0 {
            0
        } else {
            n_functions_after_loc / n_functions_before_loc * 100
        }
    );

    let token_rankings = run_tokenizer(&input_file, logger)?;

    let example_word = example_word.to_ascii_lowercase();
    let example_word_token = example_word.as_bytes();

    info!(
        "Global Bag of Words generated. Checking for example word '{}'",
        example_word
    );
    info!(
        "  The token '{}' appears {} times and is ranked {} in the global Bag of Words.",
        example_word,
        token_rankings
            .get(example_word_token)
            .map(|(count, _)| *count)
            .unwrap_or(0),
        token_rankings
            .get(example_word_token)
            .map(|(_, rank)| *rank)
            .unwrap_or(0)
    );

    Ok(())
}

pub fn run_tokenizer(
    input_file: &DataFrame,
    //output_path: &str,
    //language: &str,
    _logger: &Logger, //not used currently but hopefully will later
) -> Result<HashMap<Vec<u8>, (usize, usize)>> {
    //No checks for language yet. Just uses java for now. Will add more languages later.

    let global_bow = global_counter(input_file)?;

    let token_rankings: std::collections::HashMap<Vec<u8>, (usize, usize)> =
        global_bow.token_rankings();

    Some(token_rankings).ok_or_else(|| anyhow!("No tokens found in the global Bag of Words."))
}

fn global_counter(input_file: &DataFrame) -> Result<Bow> {
    let word_matcher: Matcher = Matcher::words_matcher();
    let mut global_bow: Bow = Bow::new();

    for row in input_file
        .column("path")
        .and_then(|c| c.str())
        .unwrap()
        .into_iter()
    {
        match row {
            Some(path) => {
                //let function_code = std::fs::read_to_string(path)?;
                match load_file(path, 1024 * 1024 * 1024) {
                    Ok(Ok(function_code)) => {
                        let local_bow =
                            word_matcher.bag_of_words(&function_code.to_ascii_lowercase());
                        global_bow.merge(local_bow);
                    }
                    Ok(Err(_e)) => {
                        info!("  Warning: File to large at path {}", path);
                    }
                    Err(_e) => {
                        info!("  Warning: Could not load file at path {}", path);
                    }
                }
            }
            None => {
                info!("  Warning: Path not found");
            }
        }
    }

    Ok(global_bow)
}

/* fn tokenize_function(
    function_code_path: &str,
    separators: &Vec<&str>,
    logger: &mut Logger
) -> Result<(HashMap<String, usize>), Error> {
    let function_string = std::fs::read_to_string(function_code_path)?;


    let mut tokenized_string = function_string.clone();
    for separator in separators {
        tokenized_string = tokenized_string.replace(separator, " ");
    }

    let words_in_string: Vec<&str> = tokenized_string.split_whitespace().collect();

    let mut counts: std::collections::HashMap<String, usize> = std::collections::HashMap::new();

    for word in words_in_string {
        *counts.entry(word.to_string()).or_insert(0) += 1;
    }

    Ok(counts)
} */
