use crate::phases::tokenizer::global_counter;
use crate::utils::fs::*;
use crate::utils::inverted_index::*;
use crate::utils::logger::Logger;
use crate::utils::regex::*;
use anyhow::{/* Error,  */ Result};
use blake3;
use clap::{Arg, Command};
use core::f64;
use polars::prelude::*;
use std::cmp::Reverse;
use std::collections::HashMap;
use std::vec;
use tracing::info;

pub fn cli() -> Command {
    Command::new("type_3_duplicate_files")
        .about("Detects type 3 clones by building an index based on the most common tokens in the functions and their frequencies.")
        .disable_version_flag(true)
        .arg(
            Arg::new("input")
                .short('i')
                .long("input")
                .help("Path to the input CSV file generated by the parser.")
                .required(true),
        )
        .arg(
            Arg::new("output")
                .short('o')
                .long("output")
                .help("Path to the output CSV file to store unique files metadata.")
                .required(false),
        )
        .arg(
            Arg::new("map")
                .short('m')
                .long("map")
                .help("Path to the map CSV file to store the mapping of clones to their originals.")
                .required(false),
        )
        .arg(
            Arg::new("logs")
                .short('l')
                .long("logs")
                .help("Path to the logs file to store error logs.")
                .required(false),
        )
        .arg(
            Arg::new("languages")
                .short('g')
                .long("languages")
                .help("Comma-separated list of languages to consider. If not provided, all languages will be considered.")
                .required(false),
        )
        .arg(
            Arg::new("threads")
                .short('n')
                .help("Number of threads to use, default is 1.")
                .default_value("1")
                .value_parser(clap::value_parser!(usize))
        )
        .arg(
            Arg::new("p_prefix")
                .short('p')
                .long("p_prefix")
                .default_value("1")
                .help("Number of tokens to consider for the prefix. Default is 1.")
                .value_parser(clap::value_parser!(usize))
        )
        .arg(
            Arg::new("threshold")
                .short('t')
                .long("threshold")
                .help("Similarity threshold. Default is 0.8.")
                .default_value("0.8")
                .value_parser(clap::value_parser!(f64))
        )
        .arg(
            Arg::new("example_word")
                .short('e')
                .long("example-word")
                .help("An example word to check the global Bag of Words for.")
                .required(false),
        )
}

pub fn run(
    input_path: &str, //The path to the input CSV file storing the file paths, output of the parser phase
    _output_path: Option<&str>, //optional path to the output CSV file to store unique files metadata.
    _map_path: Option<&str>, //optional path to the map CSV file to store the mapping of clones to their originals.
    _logs_path: Option<&str>, //for error logs, not implemented yet
    /* _opt_languages: Option<Vec<&str>>, //optional list of languages. Currently java is hardcoded */
    _threads: usize,               //current implementation is single-threaded
    p_prefix: usize,               //number of tokens to consider for the prefix, default is 1
    threshold: f64,                //threshold for the prefix length, default is 0.8
    example_word: Option<&String>, //an example word to check the global Bag of Words for, optional
    _logger: &Logger,
) -> Result<()> {
    let language = "java";
    let minimum_loc = 5; //temporary
    let mut input_file = open_csv(
        input_path,
        Some(Schema::from_iter(vec![
            Field::new("id".into(), DataType::UInt32),
            Field::new("path".into(), DataType::String),
            Field::new("name".into(), DataType::String),
            Field::new("position".into(), DataType::String),
            Field::new("loc".into(), DataType::UInt32),
            Field::new("words".into(), DataType::UInt32),
        ])),
        Some(vec![
            "id", "path", "name", "position", "language", "loc", "words",
        ]),
    )?;

    let n_functions_before_language = input_file.height();
    info!(
        "{} functions found in the input file, filtering by selected language",
        n_functions_before_language
    );

    //input_file = input_file.filter(&input_file.column("language")?.equal(language));
    input_file = input_file
        .lazy()
        .filter(col("language").eq(lit(language)))
        .collect()?;

    let n_functions_after_language = input_file.height();
    info!(
        "  {} files found after filtering ({:.2} %)",
        n_functions_after_language,
        if n_functions_before_language == 0 {
            0
        } else {
            (n_functions_after_language as f64 / n_functions_before_language as f64 * 100.0)
                as usize
        }
    );
    let n_functions_before_loc = input_file.height();

    info!(" {} functions found after filtering by language, filtering functions with less that {} lines of code.", n_functions_before_loc, minimum_loc);

    //input_file = input_file.filter(&input_file.column("loc")?.greater_equal(minimum_loc))?;

    input_file = input_file
        .lazy()
        .filter(col("loc").gt_eq(lit(minimum_loc)))
        .collect()?;

    let n_functions_after_loc = input_file.height();

    info!(
        "{} functions found after filtering  ({:.2} %)", //something is weird with the percentage calculation here.
        n_functions_after_loc,
        if n_functions_before_loc == 0 {
            0
        } else {
            (n_functions_after_loc as f64 / n_functions_before_loc as f64 * 100.0) as usize
        }
    );
    let global_bow = global_counter(&input_file)?;
    let token_rankings = global_bow.token_rankings();
    let vector_of_indices_plus_min_max =
        index_builder(&input_file, token_rankings, p_prefix, threshold)?;
    // Maximum and minimum 'words' in input file
    let vector_of_indices = vector_of_indices_plus_min_max.0;
    let min_words = vector_of_indices_plus_min_max.1 .0;
    let max_words = vector_of_indices_plus_min_max.1 .1;
    info!(
        "Built {} indices with prefix scheme from 1 to {}, minimum words in a function: {}, maximum words in a function: {}.",
        vector_of_indices.len(),
        p_prefix,
        min_words,
        max_words
    );

    if let Some(word) = example_word {
        let word = word.to_owned().as_bytes().to_ascii_lowercase();
        let mut index_number = 1;
        for index in vector_of_indices.iter() {
            info!(
                "Index {} has {} entries, total length of vectors in entries: {}",
                index_number,
                index.len(),
                index.len_tokens()
            );
            if let Some(entries) = index.get(&word) {
                info!(
                    "Entries for the example word '{}' in index {}§:",
                    String::from_utf8_lossy(&word),
                    index_number
                );
                for (function_id, count) in entries {
                    info!("Function ID: {}, Count: {}", function_id, count);
                }
            } else {
                info!(
                    "The example word '{}' was not found in index {}.",
                    String::from_utf8_lossy(&word),
                    index_number
                );
            }
            index_number += 1;
        }
    }

    //go through input file again? Means i can grab 'words' from the file. Could do something like just checking candidates

    Ok(())
}

fn index_builder(
    input_file: &DataFrame,
    token_rankings: HashMap<Vec<u8>, (usize, usize)>,
    p_prefix: usize,
    threshold: f64,
) -> Result<(Vec<InvertedIndex>, (usize, usize))> {
    let word_matcher: Matcher = Matcher::words_matcher();

    let mut vector_of_indices: Vec<InvertedIndex> = Vec::new();
    for _i in 1..=p_prefix {
        vector_of_indices.push(InvertedIndex::new());
        //info!("Initialized index {}.", _i);
    }
    let mut min_words = usize::MAX;
    let mut max_words = 0;
    for path in input_file
        .column("path")
        .and_then(|c| c.str())
        .unwrap()
        .into_iter()
        .flatten()
    {
        match load_file(path, 1024 * 1024 * 1024) {
            Ok(Ok(function_code)) => {
                let local_bow = word_matcher.bag_of_words(&function_code.to_ascii_lowercase());
                let mut vectored_bow = local_bow.vectorize();
                vectored_bow.sort_by_key(|(token, _)| {
                    Reverse(
                        token_rankings
                            .get(token)
                            .map(|(_, rank)| *rank)
                            .unwrap_or(usize::MAX),
                    )
                });
                let codeblock_length = vectored_bow.iter().map(|(_, count)| count).sum::<usize>();

                // Min and Max codeblock are in number of words, not tokens but seeing as they're only used for estimating verification cost they don't need to be precise
                if codeblock_length < min_words {
                    min_words = codeblock_length;
                }
                if codeblock_length > max_words {
                    max_words = codeblock_length;
                }
                let _verification_cost_per_candidate_estimate =
                    (min_words as f64 + max_words as f64) / 2.0;
                //Temporarily shut off so the compiler doesn't complain about unused variables, will be used later
                let prefix_length =
                    codeblock_length - ((codeblock_length as f64) * threshold).round() as usize + 1;

                let mut cumulative_count = 0;
                let mut p = 1;
                let function_id = blake3::hash(path.as_bytes());
                //info!("Prefix length: {}, total tokens: {}, codeblock length: {}", prefix_length, vectored_bow.len(), codeblock_length);

                for (token, count) in vectored_bow {
                    cumulative_count += count;
                    vector_of_indices[p - 1].add(&token, count, function_id);
                    if cumulative_count >= prefix_length {
                        if p == p_prefix {
                            //info!("Prefix scheme {} added token {} with count {}", p, String::from_utf8_lossy(&token), count);
                            break;
                        } else {
                            p += 1;
                        }
                    }
                }
            }
            Ok(Err(_e)) => {
                info!("Warning: File too large at path '{}', skipping.", path);
            }
            Err(_e) => {
                info!("Failed to read file at path '{}', skipping.", path);
            }
        }
    }
    info!("Finished building indices.");
    Ok((vector_of_indices, (min_words, max_words)))
}

/* fn delta_filter_cost(
    prefix_vector: &Vec<(Vec<u8>, usize)>,
    vector_of_indices: &Vec<InvertedIndex>,
    p_prefix: usize,
    &previous_cost: &usize,
) -> usize {
    let mut cost = 0;
    if p_prefix == 1 {
        for (token, _) in prefix_vector {
            cost += vector_of_indices[0].token_frequency(token, false);
        }
    } else {
        let last_token = prefix_vector.last().unwrap().0.clone();
        for (token, _) in prefix_vector {
            cost += vector_of_indices[p_prefix - 1].token_frequency(token, false);
        }
        for p in 1..(p_prefix - 1) {
            // the previous for-loop already counted the last token for the current inverted_index
            cost += vector_of_indices[p - 1].token_frequency(&last_token, false);
        }
    }
    let total_cost = previous_cost + cost;
    total_cost
} */
