use crate::phases::tokenizer::global_counter;
use crate::utils::candidate_map::*;
use crate::utils::fs::*;
use crate::utils::inverted_index::*;
use crate::utils::logger::Logger;
use crate::utils::regex::*;
use anyhow::{/* Error,  */ Result};
use blake3;
use clap::{Arg, Command};
use core::f64;
use either::Either;
use polars::prelude::*;
use std::cmp::{max, min};
use std::collections::{HashMap, HashSet};
use std::vec;
use tracing::info;

type CloneMap = HashMap<blake3::Hash, Either<HashSet<blake3::Hash>, blake3::Hash>>;

pub fn cli() -> Command {
    Command::new("type_3_duplicate_files")
        .about("Detects type 3 clones by building an index based on the most common tokens in the functions and their frequencies.")
        .disable_version_flag(true)
        .arg(
            Arg::new("input")
                .short('i')
                .long("input")
                .help("Path to the input CSV file generated by the parser.")
                .required(true),
        )
        .arg(
            Arg::new("output")
                .short('o')
                .long("output")
                .help("Path to the output CSV file to store unique files metadata.")
                .required(false),
        )
        .arg(
            Arg::new("map")
                .short('m')
                .long("map")
                .help("Path to the map CSV file to store the mapping of clones to their originals.")
                .required(false),
        )
        .arg(
            Arg::new("logs")
                .short('l')
                .long("logs")
                .help("Path to the logs file to store error logs.")
                .required(false),
        )
        .arg(
            Arg::new("language")
                .short('g')
                .long("languages")
                /* .help("Comma-separated list of languages to consider. If not provided, all languages will be considered.") */
                .help("language as a string, e.g. 'java'. If not provided, defaults to 'java'. TODO")
                .required(false),
        )
        .arg(
            Arg::new("threads")
                .short('n')
                .help("Number of threads to use, default is 1.")
                .default_value("1")
                .value_parser(clap::value_parser!(usize))
        )
        .arg(
            Arg::new("p_prefix")
                .short('p')
                .long("p_prefix")
                .default_value("1")
                .help("Number of tokens to consider for the prefix. Default is 1.")
                .value_parser(clap::value_parser!(usize))
        )
        .arg(
            Arg::new("threshold")
                .short('t')
                .long("threshold")
                .help("Similarity threshold. Default is 0.8.")
                .default_value("0.8")
                .value_parser(clap::value_parser!(f64))
        )
        .arg(
            Arg::new("example_word")
                .short('e')
                .long("example-word")
                .help("An example word to check the global Bag of Words for.")
                .required(false),
        )
}

pub fn run(
    input_path: &str, //The path to the input CSV file storing the file paths, output of the parser phase
    _output_path: Option<&str>, //optional path to the output CSV file to store unique files metadata.
    _map_path: Option<&str>, //optional path to the map CSV file to store the mapping of clones to their originals.
    _logs_path: Option<&str>, //for error logs, not implemented yet
    /* _opt_languages: Option<Vec<&str>>, //optional list of languages. Currently java is hardcoded */
    opt_language: Option<&str>,
    _threads: usize,               //current implementation is single-threaded
    p_prefix: usize,               //number of tokens to consider for the prefix, default is 1
    threshold: f64,                //threshold for the prefix length, default is 0.8
    example_word: Option<&String>, //an example word to check the global Bag of Words for, optional
    _logger: &Logger,
) -> Result<()> {
    //let language = "java";
    let language = opt_language.unwrap_or("java"); //default to java currently
    let minimum_loc = 2; //temporary
    let mut input_file = open_csv(
        input_path,
        Some(Schema::from_iter(vec![
            Field::new("id".into(), DataType::UInt32),
            Field::new("path".into(), DataType::String),
            Field::new("name".into(), DataType::String),
            Field::new("position".into(), DataType::String),
            Field::new("loc".into(), DataType::UInt32),
            Field::new("words".into(), DataType::UInt32),
        ])),
        Some(vec![
            "id", "path", "name", "position", "language", "loc", "words",
        ]),
    )?;

    let n_functions_before_language = input_file.height();
    info!(
        "{} functions found in the input file, filtering by selected language",
        n_functions_before_language
    );

    //input_file = input_file.filter(&input_file.column("language")?.equal(language));
    input_file = input_file
        .lazy()
        .filter(col("language").eq(lit(language)))
        .collect()?;

    let n_functions_after_language = input_file.height();
    info!(
        "  {} files found after filtering ({:.2} %)",
        n_functions_after_language,
        if n_functions_before_language == 0 {
            0
        } else {
            (n_functions_after_language as f64 / n_functions_before_language as f64 * 100.0)
                as usize
        }
    );
    let n_functions_before_loc = input_file.height();

    info!(" {} functions found after filtering by language, filtering functions with less that {} lines of code.", n_functions_before_loc, minimum_loc);

    //input_file = input_file.filter(&input_file.column("loc")?.greater_equal(minimum_loc))?;

    input_file = input_file
        .lazy()
        .filter(col("loc").gt_eq(lit(minimum_loc)))
        .collect()?;

    let n_functions_after_loc = input_file.height();

    info!(
        "{} functions found after filtering  ({:.2} %)", //something is weird with the percentage calculation here.
        n_functions_after_loc,
        if n_functions_before_loc == 0 {
            0
        } else {
            (n_functions_after_loc as f64 / n_functions_before_loc as f64 * 100.0) as usize
        }
    );

    //moved here from detect_clones
    let paths_column = input_file.column("path")?.str()?;
    let words_column = input_file.column("words")?.u32()?;
    let rows: Vec<(&str, usize)> = paths_column
        .into_iter()
        .zip(words_column)
        .filter_map(|(path_opt, words_opt)| match (path_opt, words_opt) {
            (Some(path), Some(words)) => Some((path, words as usize)),
            _ => None,
        })
        .collect();

    let function_paths_and_lengths: HashMap<blake3::Hash, (&str, usize)> = rows
        .iter()
        .map(|(path, words)| (blake3::hash(path.as_bytes()), (*path, *words)))
        .collect();

    let global_bow = global_counter(&input_file)?;
    let token_rankings = global_bow.token_rankings();
    let vector_of_indices_plus_min_max = index_builder(
        &input_file,
        &token_rankings,
        p_prefix,
        threshold,
        &function_paths_and_lengths,
    )?;
    // Maximum and minimum 'words' in input file
    let vector_of_indices = vector_of_indices_plus_min_max.0;
    let min_words = vector_of_indices_plus_min_max.1 .0;
    let max_words = vector_of_indices_plus_min_max.1 .1;
    info!(
        "Built {} indices with prefix scheme from 1 to {}, minimum words in a function: {}, maximum words in a function: {}.",
        vector_of_indices.len(),
        p_prefix,
        min_words,
        max_words
    );

    if let Some(word) = example_word {
        let word = word.to_owned().as_bytes().to_ascii_lowercase();
        let mut index_number = 1;
        for index in vector_of_indices.iter() {
            info!(
                "Index {} has {} entries, total length of vectors in entries: {}",
                index_number,
                index.len(),
                index.len_tokens()
            );
            if let Some(entries) = index.get(&word) {
                info!(
                    "Entries for the example word '{}' in index {}§:",
                    String::from_utf8_lossy(&word),
                    index_number
                );
                for (function_id, count, (token_position, cumulative_count)) in entries {
                    info!(
                        "Function ID: {}, Count: {}, Token Position: {}, Cumulative Count: {}",
                        function_id, count, token_position, cumulative_count
                    );
                }
            } else {
                info!(
                    "The example word '{}' was not found in index {}.",
                    String::from_utf8_lossy(&word),
                    index_number
                );
            }
            index_number += 1;
        }
    }

    //go through input file again? Means i can grab 'words' from the file. Could do something like just checking candidates
    let clone_map = detect_clones(
        &token_rankings,
        &vector_of_indices,
        threshold,
        &function_paths_and_lengths,
    )?;
    info!(
        "Finished detecting clones. {} clones found.",
        clone_map.len()
    );
    Ok(())
}

fn index_builder(
    input_file: &DataFrame,
    token_rankings: &HashMap<Vec<u8>, (usize, usize)>,
    p_prefix: usize,
    threshold: f64,
    function_paths_and_lengths: &HashMap<blake3::Hash, (&str, usize)>,
) -> Result<(Vec<InvertedIndex>, (usize, usize))> {
    let word_matcher: Matcher = Matcher::words_matcher();

    let mut vector_of_indices: Vec<InvertedIndex> = Vec::new();
    for _i in 1..=p_prefix {
        vector_of_indices.push(InvertedIndex::new());
        //info!("Initialized index {}.", _i);
    }
    let mut min_words = usize::MAX;
    let mut max_words = 0;
    for path in input_file
        .column("path")
        .and_then(|c| c.str())
        .unwrap()
        .into_iter()
        .flatten()
    {
        match load_file(path, 1024 * 1024 * 1024) {
            Ok(Ok(function_code)) => {
                let local_bow = word_matcher.bag_of_words(&function_code.to_ascii_lowercase());
                let mut vectored_bow = local_bow.vectorize();
                vectored_bow.sort_by_key(|(token, _)| {
                    token_rankings
                        .get(token)
                        .map(|(_, rank)| *rank)
                        .unwrap_or(usize::MAX)
                });
                //let codeblock_length = vectored_bow.iter().map(|(_, count)| count).sum::<usize>();
                let codeblock_length = function_paths_and_lengths
                    .get(&blake3::hash(path.as_bytes()))
                    .map(|(_, count)| *count)
                    .unwrap_or(0);
                // Could probably rewrite this to get number of words from the input file instead of calculating it here
                // Min and Max codeblock are in number of words, not tokens but seeing as they're only used for estimating verification cost they don't need to be precise
                if codeblock_length < min_words {
                    min_words = codeblock_length;
                }
                if codeblock_length > max_words {
                    max_words = codeblock_length;
                }
                let prefix_length =
                    codeblock_length - ((codeblock_length as f64) * threshold).round() as usize + 1;

                let mut cumulative_count = 0;
                let mut p = 1;
                let function_id = blake3::hash(path.as_bytes());
                //info!("Prefix length: {}, total tokens: {}, codeblock length: {}", prefix_length, vectored_bow.len(), codeblock_length);

                for (idx, (token, count)) in vectored_bow.iter().enumerate() {
                    cumulative_count += count;
                    vector_of_indices[p - 1].add(token, function_id, *count, idx, cumulative_count);
                    if cumulative_count >= prefix_length {
                        if p == p_prefix {
                            //info!("Prefix scheme {} added token {} with count {}", p, String::from_utf8_lossy(&token), count);
                            break;
                        } else {
                            p += 1;
                        }
                    }
                }
            }
            Ok(Err(_e)) => {
                info!("Warning: File too large at path '{}', skipping.", path);
            }
            Err(_e) => {
                info!("Failed to read file at path '{}', skipping.", path);
            }
        }
    }
    info!("Finished building indices.");
    Ok((vector_of_indices, (min_words, max_words)))
}

fn delta_filter_cost(
    token_tuple: &(Vec<u8>, usize),
    vector_of_indices: &[InvertedIndex], //changed from &Vec<InvertedIndex> since the compiler requested it
    p_prefix: usize,
    new: bool,
) -> usize {
    let token = &token_tuple.0;
    let mut cost = 0;
    if new {
        //if the token is new to the prefix, we need to count its frequency in all previous delta indices
        for p in 1..=p_prefix {
            cost += vector_of_indices[p - 1].token_frequency(token, false);
        }
    } else {
        //just count the frequency in the new delta index
        cost += vector_of_indices[p_prefix - 1].token_frequency(token, false);
    }
    cost
}

fn weighted_prefix_end(vectored_bow: &[(Vec<u8>, usize)], prefix_length: usize) -> usize {
    if prefix_length == 0 {
        info!("Prefix length is 0, returning 0 for weighted prefix end.");
        // This case shouldn't be seen
        return 0;
    }
    let mut cumulative_count = 0usize;
    for (idx, (_, count)) in vectored_bow.iter().enumerate() {
        cumulative_count += *count;
        if cumulative_count >= prefix_length {
            return idx + 1; //Enumerator is 0-based, so we need to add 1 to get the correct length of the prefix vector
        }
    }
    info!("Warning: prefix_length {} is greater than total token count {}, returning full length of vectored_bow.", prefix_length, vectored_bow.len());
    vectored_bow.len()
}

fn detect_clones(
    token_rankings: &HashMap<Vec<u8>, (usize, usize)>,
    vector_of_indices: &[InvertedIndex], //changed from &Vec<InvertedIndex> since the compiler requested it
    threshold: f64,
    function_paths_and_lengths: &HashMap<blake3::Hash, (&str, usize)>,
) -> Result<CloneMap> {
    // result will probably be a 'clone-map'. Unsure for now if it has to be its own data-structure or if i can reuse the candidate map from before.
    let mut clone_map: CloneMap = HashMap::new();

    let word_matcher: Matcher = Matcher::words_matcher();
    let p_prefix = vector_of_indices.len();
    for (path, origin_word_count) in function_paths_and_lengths.values() {
        info!("-----------------------------------------------------------------------------");
        // info!("Path: {}, Words: {}", path, origin_word_count);
        match load_file(path, 1024 * 1024 * 1024) {
            Ok(Ok(function_code)) => {
                let local_bow = word_matcher.bag_of_words(&function_code.to_ascii_lowercase());
                let mut origin_vectored_bow = local_bow.vectorize();
                origin_vectored_bow.sort_by_key(|(token, _)| {
                    token_rankings
                        .get(token)
                        .map(|(_, rank)| *rank)
                        .unwrap_or(usize::MAX)
                });
                let origin_function_id = blake3::hash(path.as_bytes());
                info!("Origin path: {}", path);
                let mut candidate_map = CandidateMap::new();

                let prefix_length = origin_word_count
                    - ((*origin_word_count as f64) * threshold).round() as usize
                    + 1;

                let init_prefix_end = weighted_prefix_end(&origin_vectored_bow, prefix_length);
                let mut filter_cost_vector: Vec<usize> = Vec::new();
                filter_cost_vector.push(0); //cost of prefix scheme 1 is calculated from an empty prefix, so the initial cost is 0
                let mut verification_cost_vector: Vec<usize> = Vec::new();
                verification_cost_vector.push(0); //verification cost is estimated as 0 for the first prefix scheme since we haven't seen any candidates yet,
                let mut total_cost_vector: Vec<usize> = Vec::new();
                total_cost_vector.push(usize::MAX); //total cost is initially set to max since so 0-prefix can never be chosen as the best prefix scheme
                                                    // big loop, will be used for the different prefix schemes
                let mut origin_cumulative_count = 0usize;
                let mut origin_token_position = 0usize;
                'prefix_schemes: for p in 1..=p_prefix {
                    let mut filter_cost = filter_cost_vector[p - 1]; // start with the filter cost of the previous prefix scheme
                    let prefix_end = init_prefix_end + p - 1; //the prefix end for the current scheme is at least the prefix end of the first scheme + the number of tokens in the prefix - 1 (since p-prefix is at least 1)

                    /* for (idx, token_tuple) in
                    origin_vectored_bow.iter().take(prefix_end).enumerate() */
                    while origin_token_position < prefix_end
                        && origin_token_position < origin_vectored_bow.len()
                    {
                        let token_tuple = origin_vectored_bow.get(origin_token_position).unwrap();
                        //loop through the prefix vector of the current scheme, for the first scheme this is just the original prefix vector, for the next schemes this includes additional tokens
                        let is_new = origin_token_position + 1 == prefix_end;
                        origin_cumulative_count += token_tuple.1;
                        filter_cost += delta_filter_cost(token_tuple, vector_of_indices, p, is_new);
                        for candidate in vector_of_indices[p - 1]
                            .get(&token_tuple.0)
                            .unwrap_or(&Vec::new())
                        {
                            /* if candidate_id_lt_origin_id(&candidate.0, &origin_function_id) {
                                info!("DClone: SKIPPING candidate at path '{}' since it has a lower function ID than the origin.", function_paths_and_lengths.get(&candidate.0).map(|(path, _)| *path).unwrap_or("Unknown"));
                                continue; //skip candidates that have already been processed as origins
                            } */
                            if clone_map.contains_key(&candidate.0) {
                                info!("DClone: SKIPPING candidate at path '{}' since it already has an entry in clone_map.", function_paths_and_lengths.get(&candidate.0).map(|(path, _)| *path).unwrap_or("Unknown"));
                                continue;
                            }
                            let candidate_word_count = function_paths_and_lengths
                                .get(&candidate.0)
                                .map(|(_, count)| *count)
                                .unwrap_or(0);

                            if candidate_word_count
                                < ((*origin_word_count as f64) * threshold).round() as usize
                            {
                                continue; //skip candidates that are too small to reach the threshold
                            }

                            let new_matches = min(token_tuple.1, candidate.1);
                            let function_id = candidate.0;
                            let last_token_seen_pos = candidate.2; // (token_position, cumulative_count)
                            let current_threshold =
                                (max(*origin_word_count, candidate_word_count) as f64 * threshold)
                                    .round() as usize;
                            let upper_bound = min(
                                *origin_word_count - origin_cumulative_count,
                                candidate_word_count - last_token_seen_pos.1 + new_matches, //candidate.2.1 is the number of words seen up to and including this token including duplicates
                            );
                            if candidate_map.get_token_matches(&function_id) + upper_bound
                                >= current_threshold
                            {
                                candidate_map.add_pending_update(
                                    function_id,
                                    new_matches,
                                    last_token_seen_pos,
                                );
                            }
                        }
                        origin_token_position += 1;
                    }
                    if p == 1 {
                        candidate_map.apply_pending_updates(function_paths_and_lengths);
                        //apply updates for the first prefix scheme before estimating costs since it relies on min/max length
                    }
                    let verification_cost =
                        candidate_map.verification_cost_estimate(p, origin_word_count);
                    filter_cost_vector.push(filter_cost);
                    verification_cost_vector.push(verification_cost);
                    total_cost_vector.push(filter_cost + verification_cost);

                    if total_cost_vector[p] > total_cost_vector[p - 1] {
                        info!("Best prefix scheme is {} with estimated total cost of {}, filter cost: {}, verification cost: {}. Moving on to verification phase.", p - 1, total_cost_vector[p - 1], filter_cost_vector[p - 1], verification_cost_vector[p - 1]);
                        info!("The next prefix scheme {} has estimated total cost of {}, filter cost: {}, verification cost: {}.", p, total_cost_vector[p], filter_cost_vector[p], verification_cost_vector[p]);
                        verify_candidates(
                            origin_function_id,
                            &origin_vectored_bow,
                            (origin_token_position, origin_cumulative_count),
                            &mut candidate_map,
                            &mut clone_map,
                            p_prefix,
                            token_rankings,
                            threshold,
                            function_paths_and_lengths,
                        )?;
                        break 'prefix_schemes;
                    } else {
                        //apply updates
                        candidate_map.apply_pending_updates(function_paths_and_lengths);
                        if p == p_prefix {
                            //return verify_candidates(candidate_map, path, function_code, p);
                            verify_candidates(
                                origin_function_id,
                                &origin_vectored_bow,
                                (origin_token_position, origin_cumulative_count),
                                &mut candidate_map,
                                &mut clone_map,
                                p_prefix,
                                token_rankings,
                                threshold,
                                function_paths_and_lengths,
                            )?;
                            break 'prefix_schemes;
                        }
                    }
                }
                info!("Filter cost vector: {:?}", filter_cost_vector);
                info!("Verification cost vector: {:?}", verification_cost_vector);
                info!("Total cost vector: {:?}", total_cost_vector);
            }
            Ok(Err(_e)) => {
                info!("Warning: File too large at path '{}', skipping.", path);
            }
            Err(_e) => {
                info!("Failed to read file at path '{}', skipping.", path);
            }
        }
    }

    Ok(clone_map)
}

fn verify_candidates(
    origin_function_id: blake3::Hash,
    origin_vectored_bow: &Vec<(Vec<u8>, usize)>,
    prefix_origin_last_token_seen_pos: (usize, usize),
    candidate_map: &mut CandidateMap,
    clone_map: &mut CloneMap,
    p_prefix: usize,
    token_rankings: &HashMap<Vec<u8>, (usize, usize)>,
    threshold: f64,
    function_paths_and_lengths: &HashMap<blake3::Hash, (&str, usize)>,
) -> Result<()> {
    // This function will take the candidate map for a function and verify the candidates that have enough matches
    // to be considered clones based on their full token vectors.
    // The clone_map is updated with the results, mapping original function ids to sets of clone function ids.
    let word_matcher: Matcher = Matcher::words_matcher();
    let (origin_path, origin_word_count) = function_paths_and_lengths
        .get(&origin_function_id)
        .copied()
        .unwrap_or(("Unknown", 0));
    info!(
        "Verifying candidates for function at path '{}', with word count {}.",
        origin_path, origin_word_count
    );
    let origin_vectored_bow = origin_vectored_bow.to_owned();
    let origin_token_count = origin_vectored_bow.len();
    let candidates_to_verify = candidate_map.get_candidates_with_n_matches(p_prefix, "at_least"); // (token_position, cumulative_count)
    let origin_vector_readable: Vec<(String, usize)> = origin_vectored_bow
        .iter()
        .map(|(token, count)| (String::from_utf8_lossy(token).to_string(), *count))
        .collect();
    info!("sorted origin vector: {:?}", origin_vector_readable);
    info!("origin_function_id: {:?}", origin_function_id);
    info!("origin_id as bytes: {:?}", origin_function_id.as_bytes());
    for candidate_id in candidates_to_verify {
        info!("----------------------");
        let (path, length) = function_paths_and_lengths
            .get(&candidate_id)
            .copied()
            .unwrap();
        info!("candidate_id as bytes: {:?}", candidate_id.as_bytes());
        if clone_map.contains_key(&candidate_id) {
            info!(
                "SKIPPING candidate at path '{}' since it already has an entry in clone_map.",
                path
            );
            continue;
        }
        if candidate_id == origin_function_id {
            info!("Skipping self-comparison for function at path '{}'.", path);
            continue; //skip comparing the function to itself
        }
        let mut origin_last_token_seen_pos = prefix_origin_last_token_seen_pos;
        match load_file(path, 1024 * 1024 * 1024) {
            Ok(Ok(candidate_code)) => {
                // Handle successful file load
                // load function, sort tokens by global frequency, calculate similarity, if above threshold add to clone map
                info!("Candidate loaded: {}, length: {}", path, length);
                let candidate_bow = word_matcher.bag_of_words(&candidate_code.to_ascii_lowercase());
                let mut vectored_candidate_bow = candidate_bow.vectorize();
                vectored_candidate_bow.sort_by_key(|(token, _)| {
                    token_rankings
                        .get(token)
                        .map(|(_, rank)| *rank)
                        .unwrap_or(usize::MAX)
                });
                let candidate_vector_readable: Vec<(String, usize)> = vectored_candidate_bow
                    .iter()
                    .map(|(token, count)| (String::from_utf8_lossy(token).to_string(), *count))
                    .collect();
                info!("sorted candidate vector: {:?}", candidate_vector_readable);
                let candidate_word_count = length;
                let candidate_token_count = vectored_candidate_bow.len();
                let current_threshold = (max(origin_word_count, candidate_word_count) as f64
                    * threshold)
                    .round() as usize;
                let mut candidate_last_token_seen_pos =
                    candidate_map.get_last_token_seen_pos(&candidate_id); // (token_position, cumulative_count)
                let mut new_matches = 0usize;
                let prefix_matches = candidate_map.get_token_matches(&candidate_id);
                while origin_last_token_seen_pos.0 < origin_token_count
                    && candidate_last_token_seen_pos.0 < candidate_token_count
                {
                    let upper_bound = min(
                        origin_word_count - origin_last_token_seen_pos.1,
                        candidate_word_count - candidate_last_token_seen_pos.1,
                    );
                    let current_matches = prefix_matches + new_matches;
                    let origin_token_tuple = &origin_vectored_bow[origin_last_token_seen_pos.0];
                    let candidate_token_tuple =
                        &vectored_candidate_bow[candidate_last_token_seen_pos.0];

                    info!("Current threshold: {}", current_threshold);
                    info!(
                        "Current matches: {} + {} = {}",
                        prefix_matches, new_matches, current_matches
                    );
                    info!("Upper bound of remaining matches: {}", upper_bound);

                    let origin_rank = token_rankings
                        .get(&origin_token_tuple.0)
                        .map(|(_, rank)| *rank)
                        .unwrap_or(usize::MAX);
                    let candidate_rank = token_rankings
                        .get(&candidate_token_tuple.0)
                        .map(|(_, rank)| *rank)
                        .unwrap_or(usize::MAX);

                    info!(
                        "Origin: {}, rank: {}, position: {} | Candidate: {}, rank: {}, position: {}",
                        String::from_utf8_lossy(&origin_token_tuple.0),
                        origin_rank,
                        origin_last_token_seen_pos.0,
                        String::from_utf8_lossy(&candidate_token_tuple.0),
                        candidate_rank,
                        candidate_last_token_seen_pos.0
                    );

                    if current_matches >= current_threshold {
                        //already reached the threshold, we can stop comparing this candidate and add it to the clone map
                        info!(
                            "Threshold reached with current matches {}, adding to clone map.",
                            current_matches
                        );
                        break;
                    } else if upper_bound + current_matches >= current_threshold {
                        if origin_token_tuple.0 == candidate_token_tuple.0 {
                            //it's a match
                            info!("MATCHING!");
                            new_matches += min(origin_token_tuple.1, candidate_token_tuple.1);
                            candidate_last_token_seen_pos.0 += 1;
                            candidate_last_token_seen_pos.1 += candidate_token_tuple.1;
                            origin_last_token_seen_pos.0 += 1;
                            origin_last_token_seen_pos.1 += origin_token_tuple.1;
                        } else if origin_rank > candidate_rank {
                            //origin token is more frequent than candidate token, so we move in the candidate vector
                            info!("origin_count > candidate_count");
                            candidate_last_token_seen_pos.0 += 1;
                            candidate_last_token_seen_pos.1 += origin_token_tuple.1;
                        } else {
                            //candidate token is more frequent than origin token, so we move in the origin vector
                            info!("candidate_count > origin_count");
                            origin_last_token_seen_pos.0 += 1;
                            origin_last_token_seen_pos.1 += candidate_token_tuple.1;
                        }
                    } else {
                        info!("UPPER BOUND + current_matches is {}, which is not enough to reach the threshold of {}. Stopping comparison for this candidate.", upper_bound + current_matches, current_threshold);
                        info!(
                            "origin_last_token_seen_pos: {}, candidate_last_token_seen_pos: {}",
                            origin_last_token_seen_pos.0, candidate_last_token_seen_pos.0
                        );
                        break;
                    }
                }
                candidate_map.add_candidate(
                    candidate_id,
                    function_paths_and_lengths,
                    new_matches,
                    candidate_last_token_seen_pos,
                );
                if candidate_map.get_token_matches(&candidate_id) >= current_threshold {
                    insert_clone_relation(clone_map, origin_function_id, candidate_id);
                    info!("*** CLONE DETECTED! ***");
                    info!(
                        "Origin: {}, Candidate: {}, Similarity >= {:.2} %",
                        function_paths_and_lengths
                            .get(&origin_function_id)
                            .map(|(path, _)| *path)
                            .unwrap_or("Unknown"),
                        function_paths_and_lengths
                            .get(&candidate_id)
                            .map(|(path, _)| *path)
                            .unwrap_or("Unknown"),
                        (candidate_map.get_token_matches(&candidate_id) as f64
                            / max(origin_word_count, candidate_word_count) as f64)
                            * 100.0
                    );
                }
                info!("**********")
            }
            Ok(Err(_)) => {
                info!("Warning: File too large at path '{}', skipping.", path);
            }
            Err(_) => {
                info!("Failed to read file at path '{}', skipping.", path);
            }
        }
    }
    Ok(())
}

fn insert_clone_relation(
    clone_map: &mut CloneMap,
    origin_function_id: blake3::Hash,
    candidate_id: blake3::Hash,
) {
    let origin_entry = clone_map
        .entry(origin_function_id)
        .or_insert_with(|| Either::Left(HashSet::new()));

    // Origin must always store the set of its clones as Left(HashSet<_>).
    if let Either::Left(clones) = origin_entry {
        clones.insert(candidate_id);
    } else {
        *origin_entry = Either::Left(HashSet::from([candidate_id]));
    }

    // Clone points back to its origin as Right(origin_hash).
    clone_map.insert(candidate_id, Either::Right(origin_function_id));
}
